# Generated by Django 4.1 on 2022-08-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review_application", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofessionalexp",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
