name: Job Application Review CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  health-check-test:

    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
    
    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DJANGO_DEBUG: ${{ secrets.DJANGO_DEBUG }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check Syntax and Code Formatting
      run: pycodestyle --select=E1,E9 --ignore=E126 --statistics .
    - name: Run Migrations
      run: python manage.py migrate
    - name: Run Tests
      run: python manage.py test